# Generated by Django 5.1.2 on 2024-11-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_jobtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_job', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobtitle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.job_category'),
        ),
    ]
