# Generated by Django 5.1.2 on 2024-11-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_job_category_alter_profile_jobtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jobtitle',
        ),
    ]
