# Generated by Django 5.1.2 on 2024-11-22 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobtitle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.job_category'),
        ),
    ]
